---
stages:
  - name: BUILD
    inputs:
      - type: git
        branch: master
        service: ${SAMPLE_REPO}
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
        artifact_dir: ''
        build_type: shell
        script: |-
          #!/bin/bash
          bash -n *.sh
  - name: DEPLOY
    inputs:
      - type: job
        stage: BUILD
        job: Container Build
        dir_name: null
    triggers:
      - type: stage
    properties:
      - name: BLUEMIX_USER
        type: text
        value: ${BLUEMIX_USER}
      - name: BLUEMIX_PASSWORD
        type: secure
        value: ${BLUEMIX_PASSWORD}
      - name: BLUEMIX_ACCOUNT
        type: secure
        value: ${BLUEMIX_ACCOUNT}
      - name: CLUSTER_NAME
        type: text
        value: ${CLUSTER_NAME}
      - name: API_KEY
        type: secure
        value: ${API_KEY}
    jobs:
     - name: Deploy Kubernetes Pod
       type: deployer
       target:
        region_id: ${PROD_REGION_ID}
        api_key: ${API_KEY}
        kubernetes_cluster: ${PROD_CLUSTER_NAME}
       script: |
          #!/bin/bash
          . ./scripts/deploy-to-bluemix/install.sh
          ./scripts/deploy-to-bluemix/bx_auth.sh
          ./scripts/deploy-to-bluemix/deploy.sh
hooks:
  - enabled: true
    label: null
    ssl_enabled: false
    url: >-
      https://devops-api-integration.stage1.ng.bluemix.net/v1/messaging/webhook/publish
